#!/usr/bin/env bash
# run-vm.sh — Launch the VAST VMS virtual machine under QEMU/KVM.
#
# VM spec (from lb-rocky8.7-release-5-3-2-sp4-1946523-pre-deployed.ovf):
#   vCPUs   : 16  (1 core/socket, no SMT)
#   RAM     : 128 GiB
#   Disk    : 1 TiB, SCSI (originally VirtualSCSI / pvscsi)
#   NIC     : 1x VmxNet3 on DevOps-MGMT → mapped to virtio-net-pci
#   Firmware: BIOS (not UEFI)
#   Chipset : i440fx (OVF: i440bxHostBridge / vmx-17 hw)
#
# Disk translation:
#   The original SCSI disk presents as /dev/sda inside the guest.
#   We use virtio-scsi which preserves /dev/sda naming, keeping grub and
#   fstab intact.  Do NOT use virtio-blk (-drive if=virtio) — that would
#   rename the disk to /dev/vda and the VM won't boot.
#
# NIC translation:
#   QEMU does not emulate VmxNet3.  Rocky 8.7 ships with in-kernel virtio-net
#   drivers so virtio-net-pci works out of the box with no guest changes.
#   If the guest ever fails to find the NIC, fall back to -device e1000.
#
# Networking modes (set NET_MODE below):
#   "user"   — QEMU user-mode NAT.  VM gets 10.0.2.15 via QEMU's built-in
#              DHCP.  Selected ports are forwarded from the host.  Zero host
#              setup required.  Use this first.
#
#   "bridge" — VM attaches to a host bridge (e.g. br0).  VM gets a real IP
#              on your LAN / VLAN and is directly reachable.  Required if the
#              VMS image has a hardcoded static IP that user-mode NAT can't
#              reach, or if VAST's internal networking needs real L2.
#              Requires a pre-configured bridge on the host (see below).
#
# Data disk:
#   VAST uses raw block devices as storage.  Pass the second host disk
#   (DATA_DISK below) directly into the VM as a second SCSI drive so VAST
#   can initialise its storage backend.  Double-check the device path with
#   `lsblk` before running — writing to the wrong device is destructive.
#
# Usage:
#   ./scripts/run-vm.sh                    # launch in background (daemonized)
#   ./scripts/run-vm.sh --fg               # launch in foreground (serial console)
#   ./scripts/run-vm.sh --dry-run          # print command, do not execute
#
# Connecting to the serial console once running:
#   nc -U /tmp/vast-vm-console.sock        # or:
#   socat -,raw,echo=0 UNIX-CONNECT:/tmp/vast-vm-console.sock
#
# Connecting to the QEMU monitor:
#   nc -U /tmp/vast-vm-monitor.sock        # or:
#   socat - UNIX-CONNECT:/tmp/vast-vm-monitor.sock
#
# Port forwards (user-mode NAT only):
#   Host 2443  → Guest 443   (VMS HTTPS / REST API)
#   Host 8443  → Guest 8443  (VMS alternate HTTPS port)
#   Host 2222  → Guest 22    (SSH)
#
# Setting up a host bridge for bridge mode:
#   ip link add br0 type bridge
#   ip link set br0 up
#   ip addr add 192.168.100.1/24 dev br0   # or use your LAN interface
#   # Then set BRIDGE_IFACE=br0 below and NET_MODE=bridge

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration — edit these for your environment
# ---------------------------------------------------------------------------

# Path to the converted qcow2 boot disk.
BOOT_DISK="${BOOT_DISK:-./vast-vms.qcow2}"

# NoCloud seed ISO generated by prepare-cloudinit.sh.
# If present it is attached as a CD-ROM and cloud-init uses it for
# provisioning (installs Docker, runs the VAST bootstrap).
# Set to "" to skip attaching a seed ISO.
SEED_ISO="${SEED_ISO:-./vast-seed.iso}"

# Second host disk to pass through as VAST storage (~2 TiB NVMe).
# Set to "" to skip attaching a data disk.
# WARNING: verify with `lsblk` — this device will be written to by VAST.
DATA_DISK="${DATA_DISK:-/dev/nvme2n1}"

# Networking: "user" (NAT) or "bridge"
NET_MODE="${NET_MODE:-user}"

# Bridge interface name (only used when NET_MODE=bridge)
BRIDGE_IFACE="${BRIDGE_IFACE:-br0}"

# TAP device name to create (only used when NET_MODE=bridge)
TAP_DEV="${TAP_DEV:-tap-vast}"

# Host ports for user-mode NAT port forwarding
PORT_HTTPS="${PORT_HTTPS:-2443}"      # → guest 443
PORT_ALT_HTTPS="${PORT_ALT_HTTPS:-8443}"  # → guest 8443
PORT_SSH="${PORT_SSH:-2222}"          # → guest 22

# vCPUs and RAM (matching OVF spec; reduce if needed for other workloads)
VM_CPUS="${VM_CPUS:-16}"
VM_MEM_MB="${VM_MEM_MB:-131072}"      # 128 GiB

# Runtime socket/pid paths
CONSOLE_SOCK="${CONSOLE_SOCK:-/tmp/vast-vm-console.sock}"
MONITOR_SOCK="${MONITOR_SOCK:-/tmp/vast-vm-monitor.sock}"
PID_FILE="${PID_FILE:-/tmp/vast-vm.pid}"

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

FOREGROUND=false
DRY_RUN=false

for arg in "$@"; do
    case "$arg" in
        --fg|--foreground) FOREGROUND=true ;;
        --dry-run)         DRY_RUN=true ;;
        --help|-h)
            sed -n '/^# Usage:/,/^[^#]/p' "$0" | grep '^#' | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) echo "Unknown argument: $arg" >&2; exit 1 ;;
    esac
done

# ---------------------------------------------------------------------------
# Validate inputs
# ---------------------------------------------------------------------------

if [[ ! -f "$BOOT_DISK" ]]; then
    echo "ERROR: Boot disk not found: $BOOT_DISK" >&2
    echo ""
    echo "If you have the OVA, extract and convert the VMDK:" >&2
    echo "  tar xf vast-vms.ova" >&2
    echo "  qemu-img convert -f vmdk -O qcow2 -p \\" >&2
    echo "    lb-rocky8.7-release-5-3-2-sp4-1946523-pre-deployed-disk1.vmdk \\" >&2
    echo "    vast-vms.qcow2" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Build the QEMU command
# ---------------------------------------------------------------------------

CMD=(
    qemu-system-x86_64

    # --- Machine and firmware ---
    # i440fx matches the OVF i440bxHostBridge motherboard.
    # BIOS firmware (OVF: firmware=bios, efiSecureBootEnabled=false).
    -machine pc,accel=kvm
    -cpu host

    # --- CPU and RAM ---
    # OVF: 16 vCPUs, 1 core/socket, simultaneousThreads=1 (no SMT).
    -smp "${VM_CPUS},sockets=${VM_CPUS},cores=1,threads=1"
    -m "${VM_MEM_MB}"

    # --- SCSI controller ---
    # Use QEMU's VMware PVSCSI emulation — exactly what the vendor initramfs
    # expects (vmw_pvscsi driver).  virtio-scsi and lsi53c895a both fail
    # because neither driver is in the pre-deployed initramfs.
    -device pvscsi,id=scsi0

    # --- Boot disk ---
    -drive "file=${BOOT_DISK},format=qcow2,if=none,id=boot-drive,cache=writeback,aio=threads"
    -device "scsi-hd,drive=boot-drive,bus=scsi0.0,channel=0,scsi-id=0,lun=0"
)

# --- Data disk (optional) ---
# Attach the second physical disk as SCSI 0:1 so VAST can use it for storage.
# Using format=raw with cache=none and aio=native for full disk throughput.
if [[ -n "$DATA_DISK" ]]; then
    if [[ ! -e "$DATA_DISK" ]]; then
        echo "WARNING: Data disk not found: $DATA_DISK — skipping." >&2
    else
        CMD+=(
            -drive "file=${DATA_DISK},format=raw,if=none,id=data-drive,cache=none,aio=native"
            -device "scsi-hd,drive=data-drive,bus=scsi0.0,channel=0,scsi-id=1,lun=0"
        )
        echo "Attaching data disk: $DATA_DISK"
    fi
fi

# --- cloud-init NoCloud seed ISO (optional) ---
# Attach as an IDE CD-ROM labelled "cidata" so cloud-init's NoCloud datasource
# picks it up automatically.  Generated by scripts/prepare-cloudinit.sh.
if [[ -n "$SEED_ISO" ]]; then
    if [[ ! -f "$SEED_ISO" ]]; then
        echo "WARNING: Seed ISO not found: $SEED_ISO — skipping cloud-init seed." >&2
        echo "         Run ./scripts/prepare-cloudinit.sh to generate it." >&2
    else
        CMD+=(
            -drive "file=${SEED_ISO},format=raw,if=none,id=seed-drive,readonly=on"
            -device "ide-cd,drive=seed-drive"
        )
        echo "Attaching cloud-init seed ISO: $SEED_ISO"
    fi
fi

# --- Networking ---
if [[ "$NET_MODE" == "user" ]]; then
    CMD+=(
        -netdev "user,id=net0,\
hostfwd=tcp::${PORT_HTTPS}-:443,\
hostfwd=tcp::${PORT_ALT_HTTPS}-:8443,\
hostfwd=tcp::${PORT_SSH}-:22"
        -device "virtio-net-pci,netdev=net0"
    )
    echo "Networking: user-mode NAT"
    echo "  Host :${PORT_HTTPS}  → Guest :443  (VMS HTTPS API)"
    echo "  Host :${PORT_ALT_HTTPS} → Guest :8443 (VMS alternate HTTPS)"
    echo "  Host :${PORT_SSH}   → Guest :22   (SSH)"

elif [[ "$NET_MODE" == "bridge" ]]; then
    # Create TAP device and attach to bridge.
    # Requires CAP_NET_ADMIN or running as root.
    if ! ip link show "$BRIDGE_IFACE" &>/dev/null; then
        echo "ERROR: Bridge interface '$BRIDGE_IFACE' not found." >&2
        echo "  Create it first:" >&2
        echo "    ip link add $BRIDGE_IFACE type bridge && ip link set $BRIDGE_IFACE up" >&2
        exit 1
    fi
    ip tuntap add dev "$TAP_DEV" mode tap 2>/dev/null || true
    ip link set "$TAP_DEV" master "$BRIDGE_IFACE"
    ip link set "$TAP_DEV" up
    CMD+=(
        -netdev "tap,id=net0,ifname=${TAP_DEV},script=no,downscript=no"
        -device "virtio-net-pci,netdev=net0"
    )
    echo "Networking: bridge (${BRIDGE_IFACE} via ${TAP_DEV})"
else
    echo "ERROR: Unknown NET_MODE '${NET_MODE}' — use 'user' or 'bridge'." >&2
    exit 1
fi

# --- Console and monitor ---
CMD+=(
    -serial  "unix:${CONSOLE_SOCK},server,nowait"
    -monitor "unix:${MONITOR_SOCK},server,nowait"
)

# --- Display ---
# VNC on 127.0.0.1:5900 (display :0).
# The pre-deployed VMware image uses the VGA console, not serial — VNC is
# the only reliable way to see what the VM is doing on first boot.
#
# Connect from your Mac:
#   ssh -L 5900:127.0.0.1:5900 ubuntu@grand-crow
#   open vnc://localhost:5900        # macOS Screen Sharing / Finder > Go > Connect to Server
#   # or: brew install tiger-vnc && vncviewer localhost:5900
VNC_PORT="${VNC_PORT:-5900}"
VNC_DISPLAY=$(( VNC_PORT - 5900 ))
CMD+=( -display none -vga std -vnc "127.0.0.1:${VNC_DISPLAY}"
    # Suppress PipeWire/audio warnings — VAST has no audio needs.
    -audiodev none,id=audio0 )

# --- Daemonize (unless running in foreground) ---
if [[ "$FOREGROUND" == "false" ]]; then
    CMD+=( -daemonize -pidfile "$PID_FILE" )
fi

# ---------------------------------------------------------------------------
# Execute
# ---------------------------------------------------------------------------

echo ""
echo "Boot disk : $BOOT_DISK"
echo "vCPUs     : $VM_CPUS"
echo "RAM       : $((VM_MEM_MB / 1024)) GiB"
echo ""

if [[ "$DRY_RUN" == "true" ]]; then
    echo "--- DRY RUN — command that would be executed: ---"
    echo "${CMD[@]}"
    exit 0
fi

echo "Starting VAST VMS..."
"${CMD[@]}"

if [[ "$FOREGROUND" == "false" ]]; then
    sleep 1
    if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
        echo "VM running (PID $(cat "$PID_FILE"))"
        echo ""
        echo "Console : socat -,raw,echo=0 UNIX-CONNECT:${CONSOLE_SOCK}"
        echo "Monitor : socat - UNIX-CONNECT:${MONITOR_SOCK}"
        echo "VNC     : 127.0.0.1:${VNC_PORT} (display :${VNC_DISPLAY})"
        echo ""
        echo "View the VM console via SSH tunnel from your Mac:"
        echo "  ssh -L ${VNC_PORT}:127.0.0.1:${VNC_PORT} ubuntu@grand-crow"
        echo "  open vnc://localhost:${VNC_PORT}"
        echo ""
        echo "Once the VMS is up, find its IP via VNC, then:"
        echo "  # User-mode NAT: API is at https://localhost:${PORT_HTTPS}"
        echo "  VMS_ADDRESS=localhost:${PORT_HTTPS} ./scripts/generate.sh -u admin -p <pass> -k"
        echo "  VMS_ADDRESS=localhost:${PORT_HTTPS} VMS_TOKEN=<tok> cargo test --features integration"
    else
        echo "ERROR: VM does not appear to be running. Check QEMU output above." >&2
        exit 1
    fi
fi
